[[cards]]
term = """
What are the three types of natural hazards?
"""
definition = """
geophysical, atmospheric and hydrological
"""

[[cards]]
term = """
What is a geophysical hazard?
"""
definition = """
A hazard caused by plate tectonics, e.g earthquakes and volcanoes
"""

[[cards]]
term = """
What is an atmospheric hazard?
"""
definition = """
Hazards caused by weather events, e.g tropical storms and certain droughts.
"""

[[cards]]
term = """
What is a hydrological hazard?
"""
definition = """
Hazards caused by water, e.g storm surges and floods.
"""

[[cards]]
term = """
What is frequency/incidence?
"""
definition = """
How often an event occurs (distribution through time)
"""

[[cards]]
term = """
What is intensity?
"""
definition = """
how strong the hazard is and how damaging the effects are
"""

[[cards]]
term = """
What is magnitude?
"""
definition = """
the size of hazards
"""

[[cards]]
term = """
What is hazard distribution?
"""
definition = """
the spread of hazards over space
"""

[[cards]]
term = """
What is a multi-hazardous environment?
"""
definition = """
an area that experiences more than one hazard in a frequent occurrence and they may interact
"""

[[cards]]
term = """
What is a natural disaster?
"""
definition = """
a natural event that caused harm to the environment and people
"""

[[cards]]
term = """
What is a natural phenomena?
"""
definition = """
A natural event that poses no risk to humans
"""

[[cards]]
term = """
What is a natural hazard?
"""
definition = """
A naturally occurring threat to people and the environment
"""

[[cards]]
term = """
What are the characteristics of a natural hazard? (5)
"""
definition = """
- clear origin and distinctive effects
- little or no warning
- exposure is often involuntary (LICs)
- damage is immediately after the hazard occurs
- requires emergency response
"""

[[cards]]
term = """
How is an event recognized as a natural disaster?
"""
definition = """
any of:
- 10+ deaths
- 100+ affected
- state of emergency declared
- international aid obtained
"""

[[cards]]
term = """
What is risk?
"""
definition = """
The likelihood of harm from a hazard
"""

[[cards]]
term = """
What is a primary hazard?
"""
definition = """
The effects of a hazard event resulting directly from the event 
e.g. ground shaking from earthquake
"""

[[cards]]
term = """
What is a secondary hazard?
"""
definition = """
The effects resulting from primary 
e.g. building collapse due to ground shaking
"""

[[cards]]
term = """
What is vulnerability?
"""
definition = """
The extent to which a community or population is at risk from a hazard.
"""

[[cards]]
term = """
What is resilience?
"""
definition = """
The ability of individuals/ communities over a long period of time to withstand and recover from the effects of natural hazards
"""

[[cards]]
term = """
What impact have humans had on the frequency of natural hazards?
"""
definition = """
Increased frequency due to burning more fossil fuels, leading to more CO2 emissions, speeding up the rate of climate change (enhanced greenhouse effect), so these extreme weather events and natural hazards become more common and intense
"""

[[cards]]
term = """
What are short-term responses?
"""
definition = """
Responses immediately before, during or immediately after the hazard, e.g evacuation, search and rescue
"""

[[cards]]
term = """
What long-term responses?
"""
definition = """
Responses designed to mitigate the impacts of future storms by managing the risks, including prediction, prevention, preparedness and protection.
"""

[[cards]]
term = """
What are the two types of longterm responses?
"""
definition = """
mitigation and adaptation
"""
